version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    command: "gunicorn -w 4 -b 0.0.0.0:5000 index:app -t 90 --reload"
    ports:
      - "5000:5000"
    depends_on:
      - redis
#      - workergunicorn -w 4 -b 0.0.0.0:5000 index:app -t 90 --reload
    env_file:
      - .env

  redis:
    image: "redis:latest"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    command: "celery -A index.celery_app worker --loglevel=debug"
    depends_on:
      - redis

volumes:
  redis_data: